### ISSUE TITLE
[Usage]:Failed to infer device type

### ISSUE THREAD

**Issue by h7878778h** [vllm-project/vllm-ascend#262]
### Your current environment

```text
The output of above commands
```

### How would you like to use vllm on ascend

I refer to this guide: https://vllm-ascend.readthedocs.io/en/latest/quick_start.html

I have pulled Image: quay.io/ascend/vllm-ascend:v0.7.1rc1
run this image on Ascend environment: 

![Image](https://github.com/user-attachments/assets/3c2832d6-a797-4613-bfd0-b912d2d07c3e)

run command: vllm serve {model_path}
got an error:
```
   ...
   raise RuntimeError("Failed to infer device type")
   RuntimeError: Failed to infer device type
```

I look at vllm source code, it seems that NPU is not supported?

![Image](https://github.com/user-attachments/assets/e350231c-52d2-4720-ac92-c9597d071daf)

How can I fix this problem？

**Comment by wangxiyuan** [comment]
can you try the command in python to see if there is any error?

```
import torch
import torch_npu
```

**Comment by wiLLiaM0425000** [comment]
got another error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/__init__.py", line 19, in <module>
    from torch_npu.utils._error_code import ErrCode, pta_error
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/utils/__init__.py", line 1, in <module>
    from torch_npu import _C
ImportError: libhccl.so: cannot open shared object file: No such file or directory
```

**Comment by wangxiyuan** [comment]
`libhccl.so` contains in cann-toolkit, it's installed in docker image already. 

The error you raised here is strange, can you check `npu-smi info` to make sure the NPU works inner container?

**Comment by shen-shanshan** [comment]
> got another error:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/__init__.py", line 19, in <module>
>     from torch_npu.utils._error_code import ErrCode, pta_error
>   File "/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/utils/__init__.py", line 1, in <module>
>     from torch_npu import _C
> ImportError: libhccl.so: cannot open shared object file: No such file or directory
> ```

@h7878778h It seems like that it can't find the `xxx.so` file, you can have a try to set env variables using the commands shown below:

```bash
source /usr/local/Ascend/ascend-toolkit/set_env.sh
source /usr/local/Ascend/nnal/atb/set_env.sh
```

**Comment by yni9ht** [comment]
> > got another error:
> > ```
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> >   File "/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/__init__.py", line 19, in <module>
> >     from torch_npu.utils._error_code import ErrCode, pta_error
> >   File "/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/utils/__init__.py", line 1, in <module>
> >     from torch_npu import _C
> > ImportError: libhccl.so: cannot open shared object file: No such file or directory
> > ```
> 
> [@h7878778h](https://github.com/h7878778h) It seems like that it can't find the `xxx.so` file, you can have a try to set env variables using the commands shown below:
> 
> source /usr/local/Ascend/ascend-toolkit/set_env.sh
> source /usr/local/Ascend/nnal/atb/set_env.sh

I must run these two `source` commands in k8s before starting the model

deployment yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-ascend-2
  labels:
    app: vllm-ascend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-ascend
  template:
    metadata:
      labels:
        app: vllm-ascend
        ring-controller.atlas: ascend-910b # Add this Label, used to check job kind.
    spec:
      schedulerName: volcano
      containers:
        - name: vllm-ascend
          image: registry.gzfutureai.com/gzwl/vllm-ascend:v0.7.3rc2
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
              source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
              source /usr/local/Ascend/nnal/atb/set_env.sh && \
              vllm serve Qwen/Qwen2.5-7B-Instruct --max_model_len 26240
```
