### ISSUE TITLE
[Doc]: Add lm-eval doc for vLLM online serving test and offline datasets

### ISSUE THREAD

**Issue by Yikun** [vllm-project/vllm-ascend#566]
### 📚 The doc issue

https://vllm-ascend.readthedocs.io/en/latest/developer_guide/evaluation/using_lm_eval.html
 
- Add lm-eval section for vLLM online serving test
- Add section for offline datasets test
- Move lm-eval doc before opencompass, because many users are using it

**Comment by zhangxinyuehfad** [comment]
## lm-eval Command for vLLM online Serving
Run online service follow the [link](https://vllm-ascend.readthedocs.io/en/v0.7.3-dev/quick_start.html) 
```
lm_eval \
  --model local-completions \
  --model_args "model=Qwen/Qwen2.5-0.5B-Instruct,base_url=http://127.0.0.1:8000/v1/completions,tokenized_requests=False,max_tokens=256" \
  --tasks gsm8k \
  --output_path ./
```
## lm-eval using offline dataset
Take gsm8k as an example， set lm_eval/tasks/gsm8k/gsm8k.yaml as follows:
```
tag:
  - math_word_problems
task: gsm8k

# set dataset_path arrow or json according to the downloaded dataset
dataset_path: arrow

# set dataset_name to null
dataset_name: null
output_type: generate_until

# add dataset_kwargs 
dataset_kwargs:
  data_files:
    # train data download path
    train: /root/.cache/gsm8k-train.arrow
    # test data download path
    test: /root/.cache/gsm8k-test.arrow

training_split: train
fewshot_split: train
test_split: test
doc_to_text: 'Q: {{question}}
  A(Please follow the summarize the result at the end with the format of "The answer is xxx", where xx is the result.):'
doc_to_target: "{{answer}}" #" {{answer.split('### ')[-1].rstrip()}}"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: false
    regexes_to_ignore:
      - ","
      - "\\$"
      - "(?s).*#### "
      - "\\.$"
generation_kwargs:
  until:
    - "Question:"
    - "</s>"
    - "<|im_end|>"
  do_sample: false
  temperature: 0.0
repeats: 1
num_fewshot: 5
filter_list:
  - name: "strict-match"
    filter:
      - function: "regex"
        regex_pattern: "#### (\\-?[0-9\\.\\,]+)"
      - function: "take_first"
  - name: "flexible-extract"
    filter:
      - function: "regex"
        group_select: -1
        regex_pattern: "(-?[$0-9.,]{2,})|(-?[0-9]+)"
      - function: "take_first"
metadata:
  version: 3.0
```
